### ISSUE TITLE
Files with spaces or special characters

### ISSUE THREAD

**Issue by raphael-small** [PatrickF1/fzf.fish#265] opened 2022-10-11 14:40 UTC
Hi,

Thanks for fzf.fish, it works great, though on file completion escaping backshlashes are not added which leads to no working commands
eg. cp machin\ truc\ bidule ~ becomes cp machin truc bidule ~

Thanks

**Comment by PatrickF1** [comment] 2022-10-12 18:25
very odd I am not able to reproduce the bug. Can you follow the issue reporting template so I have more info to repro it?
https://github.com/PatrickF1/fzf.fish/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by PatrickF1** [comment] 2022-10-15 19:35
Hi @raphael-small , one possibility is that you are using a different plugin. fzf.fish often gets confused with the fish integration installed by fzf.

Closing this for now. Feel free to re-comment if you still have problems. https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish

**Closed** 2022-10-15 19:35 UTC

**Comment by raphael-small** [comment] 2022-10-17 06:52
Hi,

thanks for your reply, it's totally possible, I'll investigate
have a nice day

**Comment by raphael-small** [comment] 2022-10-19 08:07
It was indeed the fzf integration that had problems
Sorry for the noise
